version: "3.7"
services:
  mariadb:
    container_name: zuluru_mariadb
    image: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zuluru
      MYSQL_USER: zuluru
      MYSQL_PASSWORD: userpassword
    volumes:
      - zulu_mysql:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - webproxy

  zuluru:
    container_name: zuluru
    image: pl77/zuluru3:latest
    build:
      context: .
    environment:
      # following variables are to enable SSL with docker-compose-letsencrypt-nginx-proxy-companion
      LETSENCRYPT_HOST: zuluru.domain.name
      LETSENCRYPT_EMAIL: admin@domain.name
      VIRTUAL_HOST: zuluru.domain.name
    volumes:
      - zulu_root:/var/www/html
    networks:
      - webproxy

volumes:
  zulu_mysql:
    name: zulu_mysql
    driver: local
    driver_opts:
      type: none
      device: /path/to/db
      o: bind
  zulu_root:
    name: zulu_root
    driver: local
    driver_opts:
      type: none
      device: /externaldirectory/for/deployment
      o: bind
networks:
  # A network for connecting local services. 
  # I use the excellent https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
  webproxy:
    external:
      name: webproxy
