name: Build and Push to DockerHub

on:
  push:

jobs:
  hub:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: sh -c "docker build -t ${{ secrets.DOCKER_USERNAME }}/zuluru3 ${*:-.}"
      - name: Dockerize
        if: success()
        uses: manusa/actions-publish-docker@master
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/zuluru3
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
